services:

  # ------------------------
  # AIRFLOW METADATA DB
  # ------------------------
  airflow_postgres:
    image: postgres:16
    container_name: airflow_db

    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

  # ------------------------
  # STOCK DATABASE (DEINE DATEN)
  # ------------------------
  stock_postgres:
    image: postgres:16
    container_name: stock_postgres

    environment:
      POSTGRES_USER: ${STOCK_DB_USER}
      POSTGRES_PASSWORD: ${STOCK_DB_PASSWORD}
      POSTGRES_DB: ${STOCK_DB_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data


  # ------------------------
  # PGADMIN (für STOCK DB)
  # ------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: stock_pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    depends_on:
      - stock_postgres


  # ------------------------
  # AIRFLOW INIT
  # ------------------------
  airflow-init:
    image: apache/airflow:2.9.3

    depends_on:
      - airflow_postgres

    env_file:
      - .env

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow_postgres:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow
      STOCK_DB_HOST: stock_postgres
      STOCK_DB_PORT: 5432
      STOCK_DB_USER: ${STOCK_DB_USER}
      STOCK_DB_PASSWORD: ${STOCK_DB_PASSWORD}
      STOCK_DB_NAME: ${STOCK_DB_NAME}

    entrypoint: >
      bash -c "
      airflow db migrate &&
      airflow users create --username ${AIRFLOW_ADMIN_USER} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname Stefan --lastname Admin --role Admin --email ${PGADMIN_EMAIL}
      "

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src


  # ------------------------
  # AIRFLOW WEB
  # ------------------------
  airflow:
    image: apache/airflow:2.9.3

    depends_on:
      - airflow_postgres
      - airflow-init

    env_file:
      - .env

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow_postgres:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow
      STOCK_DB_HOST: stock_postgres
      STOCK_DB_PORT: 5432
      STOCK_DB_USER: ${STOCK_DB_USER}
      STOCK_DB_PASSWORD: ${STOCK_DB_PASSWORD}
      STOCK_DB_NAME: ${STOCK_DB_NAME}

    ports:
      - "127.0.0.1:8080:8080"

    command: webserver

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src


  # ------------------------
  # AIRFLOW SCHEDULER
  # ------------------------
  airflow-scheduler:
    image: apache/airflow:2.9.3

    depends_on:
      - airflow_postgres
      - airflow-init

    env_file:
      - .env

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow_postgres:5432/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow
      STOCK_DB_HOST: stock_postgres
      STOCK_DB_PORT: 5432
      STOCK_DB_USER: ${STOCK_DB_USER}
      STOCK_DB_PASSWORD: ${STOCK_DB_PASSWORD}
      STOCK_DB_NAME: ${STOCK_DB_NAME}

    command: scheduler
    volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src


volumes:
  postgres_data:
  airflow_postgres_data:
